# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'TimeLine' do

pod 'AsyncDisplayKit', '~> 1.9.7.1'
pod 'BFKit', '~> 1.9.0'
pod 'Reveal-iOS-SDK', :configurations => ['Debug']
pod 'CHTCollectionViewWaterfallLayout'

end

target 'TimeLineTests' do

end

